language: php

arch: amd64
os: linux
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - ES_VERSION="7.0.0"

jobs:
  fast_finish: true
  include:
    # Latest supported dependencies with each PHP version
    - php: 7.2
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"

    # Install all SF components in the same major version, see https://github.com/dunglas/symfony-lock
    - php: 7.4

    # Try SF ^4
    - php: 7.2
      env: SYMFONY_REQUIRE="^4"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - if [ "$SYMFONY_REQUIRE" != "" ]; then composer global require --no-progress --no-scripts --no-plugins symfony/flex; fi;
  - pecl install -f mongodb-stable
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch-plugin install -b ingest-attachment
  - /tmp/elasticsearch/bin/elasticsearch --daemonize -Epath.data=/tmp
  - .travis/wait-for-elasticsearch.sh

before_script:
  - phpenv config-add .travis/php.ini
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

